<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Meeting>
 */
class MeetingFactory extends Factory
{
    public function definition(): array
    {
        $start = now()->addDays(fake()->numberBetween(-10, 10))->setTime(fake()->numberBetween(8, 18), 0);
        $durationMinutes = fake()->randomElement([30, 45, 60, 90]);

        return [
            'start_time' => $start,
            'end_time' => $start->clone()->addMinutes($durationMinutes),
            'info' => fake()->sentence(),
            // pin will be auto-generated by DB trigger if null; set null here
            'pin' => null,
            'sessions_attended' => fake()->numberBetween(0, 20),
        ];
    }
}

